% compare density field generated by BOS with DNS
clear 
close all
clc

% time stamp to compare solution (different from time step in DNS)
time_stamp = 1;

% filepath and filename for dns
dns_filepath = '/home/shannon/a/aether/Projects/siv/analysis/data/JHU_dataset_new/256x256x128/new_h5_reshape_nz4/';
dns_filename = ['jhu_mixing_' num2str(time_stamp, '%04d') '.h5'];

% load dns data
rho_dns = h5read([dns_filepath dns_filename], '/rho');
x_dns = h5read([dns_filepath dns_filename], '/x');
y_dns = h5read([dns_filepath dns_filename], '/y');

% just pick one slice, they are all nearly identical
rho_dns = rho_dns(:,:,1);

% load bos data
bos_filepath = '/home/barracuda/a/lrajendr/Projects/camera_simulation/results/images/bos/error-analysis/dns/0/1/';
bos_filename = 'rho.mat';

rho_bos = load([bos_filepath bos_filename]);


% scaling
x_dns = x_dns * (max(rho_bos.X(:)) - min(rho_bos.X(:))) / (max(x_dns) - min(x_dns));
y_dns = y_dns * (max(rho_bos.Y(:)) - min(rho_bos.Y(:))) / (max(y_dns) - min(y_dns));
rho_dns = rho_dns * 1.225;

[X_dns, Y_dns] = meshgrid(x_dns, y_dns);
% X_dns = h5read([dns_filepath dns_filename], '/X');
% Y_dns = h5read([dns_filepath dns_filename], '/Y');

% plot dns data
figure(1)
surf(X_dns, Y_dns, rho_dns, 'linestyle', 'none');
xlabel('X (m)');
ylabel('Y (m)');
axis('tight')
view(2)
h = colorbar;
title(h, '(kg/m^3)')
% caxis([1.225 * min(rho_dns(:)), 1.225 * max(rho_dns(:))])
title('DNS');

save_figure_to_file(gcf, bos_filepath, 'dns');

% plot bos data
figure(2)
surf(rho_bos.X, rho_bos.Y, rho_bos.rho, 'linestyle', 'none');
xlabel('X (m)');
ylabel('Y (m)');
axis('tight')
view(2)
h = colorbar;
title(h, '(kg/m^3)')
% caxis([1.225 * min(rho_dns(:)), 1.225 * max(rho_dns(:))])
title('BOS');
save_figure_to_file(gcf, bos_filepath, 'bos');

rho_err_abs = zeros(size(rho_bos.rho));
rho_err_rel = zeros(size(rho_bos.rho));

% calculate absolute error
for r = 1:size(rho_bos.rho,1)
    for c = 1:size(rho_bos.rho,2)
        rho_dns_interp = interp2(X_dns, Y_dns, rho_dns, rho_bos.X(r,c), rho_bos.Y(r,c));
        rho_err_abs(r,c) = abs(rho_bos.rho(r,c) - rho_dns_interp);
        rho_err_rel(r,c) = rho_err_abs(r,c)/rho_dns_interp;
    end
end

% rho_err_abs = rho_bos.rho - rho_dns(2:2:end, 2:2:end);
% 
% % calculate relative error
% rho_err_rel = rho_err_abs./rho_dns(2:2:end, 2:2:end);

% plot absolute error
figure(3)
surf(rho_bos.X, rho_bos.Y, rho_err_abs, 'linestyle', 'none');
xlabel('X (m)');
ylabel('Y (m)');
axis('tight')
view(2)
h = colorbar;
title(h, '(kg/m^3)')
title('absolute error');
save_figure_to_file(gcf, bos_filepath, 'absolute-error');

% plot relative error
figure(4)
surf(rho_bos.X, rho_bos.Y, rho_err_rel, 'linestyle', 'none');
xlabel('X (m)');
ylabel('Y (m)');
axis('tight')
view(2)
h = colorbar;
title(h, '(%)')
title('relative error');
save_figure_to_file(gcf, bos_filepath, 'relative-error');



